name: Heroku review app
on:
  pull_request:
    types: [labeled, synchronize, reopened, closed]
    branches:
      - master
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  heroku-deploy-review:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ contains(github.event.label.*.name, 'review-app') }}

    steps:
      - run: echo "${{ toJson(github) }}"
